### PR TITLE
Improve exchange rate calculation

### PR DESCRIPTION
**Pull request by reneaaron**
I did test it with a `waveshare2in13v2` display, other displays unfortunately remain untested.

### CODE REVIEW

**Comment by AxelHamburch** [comment]
Nice, its working! I think it will help to calculate a more accurate exchange rate.

I was a bit confused by the decimal place in the exchange rate. Especially since he sometimes shows one or two. Maybe one would be enough.

The first picture shows a calculation without the changes and the other two with the change.

ZomboDroid 27042022220510
.

**Comment by AxelHamburch** [comment]
I don't think it's related, but during the tests I saw an error message in the debugger. However, it came with and without the change. That's why I'm more likely to assume that it was the lntxbot again. But for the sake of completeness I would like to mention it.
2022-04-27 21_18_26-pi@raspberrypi_ ~

**Comment by reneaaron** [comment]
Thanks for testing and your feedback @AxelHamburch! 🙌 

I agree that space is very limited and we could just displace one decimal place as this is just an additional info for the user. The final amount will be calculated with the exact exchange rate, anyways. I'll update the MR.

**Comment by AxelHamburch** [comment]
Great! What do you think @lightisfaster ?

**Comment by reneaaron** [comment]
@AxelHamburch I still need to incorporate your feedback. 😅  I'll have the MR ready later this week.

**Comment by reneaaron** [comment]
@AxelHamburch I just updated the MR. Should be ready to merge!

**Comment by lightisfaster** [comment]
Hey, looks good for me, i've test it too. Thanks for feedback @AxelHamburch. Good job @reneaaron and sorry for the delay. The alignment of the text may need to be adjusted for a display type, but this is trade off we can accept.

**Pull request merged**
