### PR TITLE
Updated Spanish translation

### PR DESCRIPTION
**Pull request by danielcharrua**
Translated almost all strings but some that have doubt, need to see the messages on screen to better understand the messages.

Is there a way to test all messages on screen?

### CODE REVIEW

**Comment by danielcharrua** [comment]
Just came across https://github.com/21isenough/LightningATM/blob/master/docs/guide/languages.md

Please leave out this PR until I can check all messages on screen.

**Comment by AxelHamburch** [comment]
I guess you haven't tested it yourself with the display yet or? The problem is the different text lengths English / Spanish. That often does not fit so well. Maybe you have to try to shorten the text a bit so that it fits better. You can also change the file directly on your RaspberryPi. Then you can also test it.

But I think we could merge that already, then you have at least a Spanish basis.

**Comment by danielcharrua** [comment]
Exactly, I have not tested yet, but this has solution. I have ordered some hardware I was missing and test it all by the end of April. Also would test it on some Raspi 3 that have at home.

You can merge this PR and then I will fix any details missing. Thank you Axel.

**Comment by AxelHamburch** [comment]
@lightisfaster
LGTM. Can merge this one?

**Comment by AxelHamburch** [comment]
@21isenough 
We should merge this one too.

**Pull request merged**
