### PR TITLE
Update example_config.ini

### PR DESCRIPTION
**Pull request by danielcharrua**
Added lnbits to `activewallet` comments, refactor `btcpay_lnd` config block and added comments.

As BTCPay is using LND REST, maybe in the future will be clearer to use in activewallet something like lnd_rest instead of btcpay_lnd and propagate the change in all files... Would be better to anyone trying to use the ATM with LND REST and without BTCPay Server.

### CODE REVIEW

**Comment by danielcharrua** [comment]
I just saw #79 that you have deleted the `lntxbot` I was going to do it also 💪

**Comment by lightisfaster** [comment]
We cannot remove lntxbot until all references to it have been eliminated.

**Comment by lightisfaster** [comment]
[btcpay] -> [btcpay_lnd]
Do you have test this change? We need to be sure btcpay is not used in the code. All references need to be updated to btcpay_lnd.

**Comment by danielcharrua** [comment]
@lightisfaster you are right 🙏 it needs to be updated also in other files (also [lnd] block). Closing and starting again.

**Pull request closed without merging**
